FROM ubuntu:20.04
# Instalar Nginx y configurar una página personalizada
RUN apt-get update && apt-get install -y nginx \
    && rm -rf /var/lib/apt/lists/*
RUN echo "<h1>Hola Mundo!!</h1>" > /var/www/html/index.html
EXPOSE 80
CMD    ["nginx", "-g", "daemon off;"]

#docker build -t mikroways/helloworld:1.0.0 -f Dockerfile.hello .
#docker run --rm -d -p 80:80 mikroways/helloworld:1.0.0