FROM nginx:1-alpine
RUN echo "<html><h1>Hola Mundo!!!!</h1></html>" > \
    /usr/share/nginx/html/index.html

#docker build -t mikroways/helloworld:1.2.0 .
#docker run -d --rm -p 80:80 mikroways/helloworld:1.2.0